name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build macOS
      run: xcodebuild clean build -project SwiftUIMultiplatform.xcodeproj -scheme "SwiftUIMultiplatform (macOS)" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO
    - name: Build iOS
      run: xcodebuild clean build -project SwiftUIMultiplatform.xcodeproj -scheme "SwiftUIMultiplatform (iOS)" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO
    - name: Build watchOS
      run: xcodebuild clean build -project SwiftUIMultiplatform.xcodeproj -scheme "SwiftUIMultiplatform (watchOS) WatchKit App" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO
    - name: Build tvOS
      run: xcodebuild clean build -project SwiftUIMultilatform.xcodeproj -scheme "SwiftUIMultiPlatform (tvOS)" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO
